# Generated by Django 4.1.2 on 2022-12-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_alter_list_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
